In [12]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
ds = pd.read_csv('Airline_Delay_Cause.csv')
ds.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",89.0,13.0,2.25,1.60,...,0.0,5.99,2.0,1.0,1375.0,71.0,761.0,118.0,0.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",62.0,10.0,1.97,0.04,...,0.0,7.42,0.0,1.0,799.0,218.0,1.0,62.0,0.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,10.0,2.73,1.18,...,0.0,4.28,1.0,0.0,766.0,56.0,188.0,78.0,0.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",66.0,12.0,3.69,2.27,...,0.0,1.57,1.0,1.0,1397.0,471.0,320.0,388.0,0.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",92.0,22.0,7.76,0.00,...,0.0,11.28,2.0,0.0,1530.0,628.0,0.0,134.0,0.0,768.0

In [7]:
ds.shape

(100000, 21)

In [9]:
display(ds.describe().T)

,count,mean,std,min,25%,50%,75%,max
year,100000.0,2020.617710,1.501914,2018.0,2019.00,2021.00,2022.00,2023.00
month,100000.0,6.531960,3.455178,1.0,4.00,7.00,10.00,12.00
arr_flights,99840.0,320.833433,908.228876,1.0,39.00,88.00,215.00,21931.00
arr_del15,99652.0,57.294274,165.204000,0.0,5.00,14.00,39.00,4142.00
carrier_ct,99840.0,19.340233,50.635184,0.0,1.93,5.35,15.00,1293.91
weather_ct,99840.0,2.127702,7.379922,0.0,0.00,0.29,1.76,266.42
nas_ct,99840.0,15.906943,54.360829,0.0,0.71,3.00,9.20,1884.42
security_ct,99840.0,0.171568,0.810006,0.0,0.00,0.00,0.00,58.69
late_aircraft_ct,99840.0,19.639993,64.653064,0.0,0.99,3.79,12.02,2069.07
arr_cancelled,99840.0,8.074379,51.573767,0.0,0.00,1.00,4.00,4951.00
arr_diverted,99840.0,0.753265,3.398723,0.0,0.00,0.00,0.00,154.00
arr_delay,99840.0,3852.557192,12349.349881,0.0,263.00,853.00,2483.00,438783.00
carrier_delay,99840.0,1399.101643,4420.878284,0.0,86.00,315.00,1001.00,162563.00
weather_delay,99840.0,223.996825,867.926815,0.0,0.00,15.00,139.00,27876.00
nas_delay,99840.0,767.285857,3051.025333,0.0,20.00,113.00,379.00,97283.00
security_delay,99840.0,8.195713,47.728957,0.0,0.00,0.00,0.00,3760.00
late_aircraft_delay,99840.0,1453.971855,5070.237151,0.0,38.00,241.00,887.00,227959.00

In [ ]:
ds.isnull().sum()

In [ ]:
ds.dtypes

In [ ]:
# Distribution of Numeric Features
numeric_features = ['arr_flights', 'arr_del15', 'carrier_ct', 'weather_ct', 'nas_ct',
                    'security_ct', 'late_aircraft_ct', 'arr_cancelled', 'arr_diverted',
                    'arr_delay', 'carrier_delay', 'weather_delay', 'nas_delay',
                    'security_delay', 'late_aircraft_delay']

for i in numeric_features:
    plt.figure(figsize=(10, 6))
    sns.histplot(ds[i], kde=True, color='blue', bins =50)
    plt.title(i)
    plt.show()

In [21]:
#number of unique values in each column
ds.nunique()
# ds["carrier"].nunique()

year                       6
month                     12
carrier                   18
carrier_name              19
airport                  381
airport_name             405
arr_flights             4307
arr_del15               1425
carrier_ct             10926
weather_ct              3026
nas_ct                 10004
security_ct              792
late_aircraft_ct       11072
arr_cancelled            526
arr_diverted              97
arr_delay              15290
carrier_delay           9333
weather_delay           3494
nas_delay               6910
security_delay           531
late_aircraft_delay     9649
dtype: int64

In [ ]:
category_features = ['carrier', 'carrier_name','airport', 'airport_name']
for i in category_features: